services:
  - type: web
    name: gemini-api-final
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: GEMINI_API_KEY
        sync: false